ARG python_version=3.10

FROM python:${python_version} AS builder
RUN python -m pip install --upgrade pip
COPY ./ObjectDetection/requirements.txt .
COPY ./src/requirements.txt requirements.core
RUN cat requirements.core >> requirements.txt && pip install --user --no-warn-script-location -r requirements.txt

FROM sherensberk/darknet:2204.550.1241-devel
ARG python_version=3.10

COPY --from=builder /root/.local /root/.local
ENV PATH=/root/.local:$PATH

RUN apt-get install -y python${python_version}

WORKDIR /service/src/
COPY ./ObjectDetection/src .
RUN rm core

WORKDIR /service/src/core
COPY ./src/ .

WORKDIR /service/src/

#ADD https://github.com/stephanecharette/DarkHelp/blob/master/src-python/DarkHelp.py ./interface/DarkHelp.py
