[tool.poetry]
name = "core"
version = "0.1.0"
description = ""
authors = ["Sherensberk <oschenberk@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
opentelemetry-distro = "^0.48b0"
grpcio = "^1.66.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
