ARG version=3.11.5
FROM python:${version} AS builder
RUN apt-get update -y && \
    apt-get install -y \
    ffmpeg \
    libsm6 \
    libxext6 
RUN python -m pip install --upgrade pip
COPY ./Camera/requirements.txt .
COPY ./src/requirements.txt requirements.core
RUN cat requirements.core >> requirements.txt && pip install --user --no-warn-script-location -r requirements.txt

FROM python:${version}

COPY --from=builder /root/.local /root/.local
ENV PATH=/root/.local:$PATH

ARG USERNAME=dev
ARG PUID=1000
ARG PGID=1000

WORKDIR /service

RUN apt-get update -y && \
    usermod -a -G dialout root && \
    usermod -a -G video root && \
    chown -R root /service

COPY ./Camera/*.deb .
RUN apt-get install -y /service/*.deb
RUN find /service/ -name "*.deb" -type f -delete

WORKDIR /service/src/
COPY  ./Camera/src/ .
RUN rm core

WORKDIR /service/src/core
COPY  ./src/ .

WORKDIR /service/src/

